name: uplift-2-build

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  api_call:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      commit_message: ${{ steps.commit_message.outputs.commit_message }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Commit Message
        id: commit_message
        run: |
          # Get the latest commit message for the pushed commit
          commit_message=$(git log -1 --pretty=format:%s)
          echo "commit_message=${commit_message}" >> $GITHUB_ENV  # Set an environment variable
          echo "Commit message: $commit_message"  # Debug statement
          # Check if the commit message starts with 'Construct'
          if [[ $commit_message == Construct* ]]; then
            echo "Construct"
          else
            echo "Exiting workflow."
            exit 78
          fi

      - name: Trigger Private Workflow
        if: contains(env.commit_message, 'Construct')
        run: |
          # Send the dispatch request
          curl -X POST \
            -H "Authorization: token ${{ secrets.UPLIFT_DISPATCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "construct-request"}' \
            https://api.github.com/repos/benBUV/canvas/dispatches

      - name: Debug Commit Message
        run: |
          echo "Commit message: ${{ env.commit_message }}"
