name: course-build

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: uplift

      - name: Run Script for Each JSON File
        run: |
          for file in uplift/headers/*.json; do
            echo "Processing file: $file"
            python uplift/your_script.py "$file"
          done
        working-directory: uplift
