name: build-request

on:
  push:
    branches:
      - main

jobs:
  api_call:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '16'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: "benBUV/uplift"  

      - name: Parse JSON
        run: |
          echo "Finding JSON files..."
          json_files=$(find main -name '*.json')  

          for json_file in $json_files; do
            echo "Processing JSON file: $json_file"
            json_contents=$(cat "$json_file")
            echo "JSON contents: $json_contents"
      - name: Trigger Private Workflow
        run: |
          # Send the dispatch request
          curl -X POST \
            -H "Authorization: token ${{ secrets.UPLIFT_DISPATCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "build-request", "data": "'$json_contents'"}' \
            https://api.github.com/repos/benBUV/canvas/dispatches
