name: build-request

on:
  push:
    branches:
      - main

jobs:
  api_call:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Commit Message
        id: commit_message
        run: |
          # Get the latest commit message for the pushed commit
          commit_message=$(git log -1 --pretty=format:%s)

          # Check if the commit message starts with 'Build'
          if [[ $commit_message == Build* ]]; then
            echo "Build"
          else
            echo "No request"
            exit 78  # Exit with a neutral status code
          fi

      - name: Trigger Private Workflow
        if: contains(steps.commit_message.outputs.commit_message, 'Build')
        run: |
          # Send the dispatch request
          curl -X POST \
            -H "Authorization: token ${{ secrets.UPLIFT_DISPATCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "build-request"}' \
            https://api.github.com/repos/benBUV/canvas/dispatches

      - name: Debug Commit Message
        run: |
          echo "Commit message: ${{ steps.commit_message.outputs.commit_message }}"

