on:
  push:
    branches:
      - main

jobs:
  trigger_private_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.UPLIFT_DISPATCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "build-request"}' \
            https://api.github.com/repos/benBUV/canvas/dispatches
