name: build-request

on:
  workflow_dispatch:
    inputs:
      json_filename:
        description: 'Name of the JSON file'
        required: true

jobs:
  build_request:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch JSON Content
        run: |
          json_filename=${{ github.event.inputs.json_filename }}
          json_contents=$(curl -sL "https://raw.githubusercontent.com/benBUV/uplift/main/$json_filename")
          echo "JSON_CONTENTS=$json_contents" >> $GITHUB_ENV
          echo "JSON Contents: $JSON_CONTENTS"
      - name: Trigger Private Workflow
        run: |
          # Send the dispatch request
          curl -X POST \
            -H "Authorization: token ${{ secrets.UPLIFT_DISPATCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "build-request"}' \
            https://api.github.com/repos/benBUV/canvas/dispatches
