name: build-request

on:
  push:
    branches:
      - main

jobs:
  build_request:
    runs-on: ubuntu-latest
    outputs:
      json_contents: ${{ steps.read_json.outputs.json_contents }}
    steps:
      - name: Find JSON files and read contents
        id: read_json
        run: |
          echo "Finding JSON files..."
          json_files=$(find -name '*.json')  
          json_contents=""
          for json_file in $json_files; do
            echo "Processing JSON file: $json_file"
            json_contents=$(cat "$json_file")
            rm "$json_file"
          done

      - name: Set JSON Contents
        run: |
          echo "JSON_CONTENTS=$json_contents" >> $GITHUB_ENV

      - name: Trigger Private Workflow
        run: |
          # Send the dispatch request
          curl -X POST \
            -H "Authorization: token ${{ secrets.UPLIFT_DISPATCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "build-request"}' \
            https://api.github.com/repos/benBUV/canvas/dispatches

  api_call:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Debug: Print JSON_CONTENTS
        run: |
          echo "JSON_CONTENTS: $JSON_CONTENTS"

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '16'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: "benBUV/canvas"  # Repository containing 'app.py'

      - name: Run Python Script
        run: |
          python uplift/app.py "$JSON_CONTENTS" "$ACCESS_TOKEN"
