on:
  push:
    branches:
      - main

jobs:
  trigger_private_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private Workflow
        uses: actions/uplift course build

        with:
          token: ${{ secrets.UPLIFT_DISPATCH }}
          repository: benBUV/canvas
          event-type: build-request
