name: build-request

on:
  push:
    branches:
      - main

jobs:
  api_call:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check Commit Message
        id: commit_message
        run: |
          # Get the latest commit message for the pushed commit
          commit_message=$(git log -1 --pretty=format:%s)

          # Check if the commit message starts with 'build'
          if [[ $commit_message == build* ]]; then
            echo "Commit message starts with 'build'. Continuing with workflow."
          else
            echo "Commit message does not start with 'build'. Exiting workflow."
            exit 78  # Exit with a neutral status code
          fi

      - name: Trigger Private Workflow
        if: contains(steps.commit_message.outputs.commit_message, 'build')
        run: |
          # Send the dispatch request
          curl -X POST \
            -H "Authorization: token ${{ secrets.UPLIFT_DISPATCH }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "build-request"}' \
            https://api.github.com/repos/benBUV/canvas/dispatches
